CREATE TABLE DADOS
	(id_dados INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	informacao VARCHAR(20) NOT NULL,
	data_hora DATETIME NOT NULL,
	valor REAL NOT NULL);

INSERT INTO DADOS (informacao, data_hora, valor)
	VALUES ('Temperatura', '2016-09-27 13:59:34', 25.67);	

SELECT * FROM DADOS;